name-template: 'v$RESOLVED_VERSION âœ¨'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ What's new'
    labels:
      - 'major'
  - title: 'ğŸ”§ Changes'
    labels:
      - 'minor'
  - title: 'ğŸ Bug Fixes'
    labels:
      - 'patch'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES